      COMPLEX CPHFAC(NRD),CF(NRD),CZUBUF(NRD),CZLBUF(NRD)
      COMMON /RECDAT/ LAY(NRD),Z(NRD),RDC(NRD),SDC(NRD),CF,
     1                LAYS(NRD),ZUS(NRD),ZLS(NRD),CPHFAC,
     2                RZUBUF(NRD),RZLBUF(NRD),CZUBUF,
     3                CZLBUF,RLIND(NRD)
      COMPLEX CSAIR1(NRD),CSAIR2(NRD),CSAIR3(NRD)
      COMMON /AIRYSC/ CSAIR1,CSAIR2,CSAIR3

