C
C     ***PLOT SIZE DATA FOR MINDIS
C     *** JOHN STEIERT   3-DEC-81
C
C          PHYXLN        HORIZONTAL PAGE SIZE (INCHES)
C          PHYYLN        VERTICAL PAGE SIZE (INCHES)
C          XAXLEN        X DIMENSION OF SUBPLOT AREA
C          YAXLEN        Y DIMENSION OF SUBPLOT AREA
C          XPHORG        X AXIS PHYSICAL ORIGIN (INCHES)
C          YPHORG        Y AXIS PHYSICAL ORIGIN (INCHES)
C          SPLAX1        SUB-PLOT AREA: LEFT X VALUE
C          SPLAX2        SUB-PLOT AREA: RIGHT X VALUE
C          SPLAY1        SUB-PLOT AREA: BOTTOM Y VALUE
C          SPLAY2        SUB-PLOT AREA: TOP Y VALUE
C          LPHORG        FLAG SHOWING IF PHYSICAL ORIGIN SPECIFIED
C          ADDXLN        DISTANCE OF X-AXIS ORIGIN FROM PHYS ORIG (INCHES)
C          ADDYLN        DISTANCE OF Y-AXIS ORIGIN FROM PHYS ORIG (INCHES)
C          XMINPT        MINIMUM X POINT DRAWN TO WITHIN PLOT AREA
C          XMAXPT        MAXIMUM Y POINT DRAWN TO WITHIN PLOT AREA
C          YMINPT        MINIMUM Y POINT DRAWN TO WITHIN PLOT AREA
C          YMAXPT        MAXIMUM Y POINT DRAWN TO WITHIN PLOT AREA
C
      REAL PHYXLN, PHYYLN, XAXLEN, YAXLEN, XPHORG, YPHORG
      REAL SPLAX1, SPLAX2, SPLAY1, SPLAY2
      REAL ADDXLN, ADDYLN
      REAL XMINPT, XMAXPT, YMINPT, YMAXPT
      LOGICAL LPHORG
      COMMON /SIZ$DT/ PHYXLN, PHYYLN, XAXLEN, YAXLEN, XPHORG,
     $                YPHORG, SPLAX1, SPLAX2, SPLAY1, SPLAY2,
     $                LPHORG, ADDXLN, ADDYLN, XMINPT, XMAXPT,
     $                YMINPT, YMAXPT
