C
C     COMMON BLOCKS OF ARRAYS THE SIZE OF WHICH DEPEND ON
C     THE MAXIMUM NUMBER OF LAYERS NLA.
C
C     LOCAL COEFFICIENT MATRICES AND RIGHT HAND SIDES
C
      COMPLEX ALO(NLA,NLEQ,NLEQ),AUP(NLA,NLEQ,NLEQ),
     &        R(NLA,NLEQ,MMAX,ISROWMAX),SS(NLA,NLEQ,MMAX,ISROWMAX),
     &        poin(NLEQH,nla,mmax),puin(NLEQH,nla,mmax)

      COMMON /FIELD/ ALO,AUP,R,SS,poin,puin
C
C     ENVIRONMENTAL PARAMETERS AND WAVENUMBERS
C
      COMPLEX AK(NLA,2),AK2(NLA,2),ALAME(NLA,2)
      COMPLEX ALFA(NLA),BETA(NLA),GAMA(NLA)
      COMPLEX ALFINV(NLA),BETINV(NLA),GAMINV(NLA)
      REAL V(NLA,6),THICK(NLA)
      COMMON /LAYDAT/ V,AK,AK2,ALAME,THICK,ALFA,BETA,GAMA,
     &                alfinv,betinv,gaminv
      COMMON /LAYTYP/ LAYTYP(NLA),NUMT(NLTYP),LAYT(NLA,NLTYP)
C
C     FUNCTIONS OF WAVENUMBERS
C
      COMPLEX EZALFM(NLA),EZBETM(NLA),EZGAMM(NLA)
      COMPLEX CON1(NLA),CON2(NLA),CON3(NLA),CON4(NLA),CON5(NLA),
     &        con6(nla)
      REAL RCON1(NLA)
      COMMON /VARS5/ LSOLF,LSOLL,NSOL,EZALFM,EZBETM,EZGAMM,
     &               RCON1,CON1,CON2,CON3,CON4,CON5,con6
C
C     MAPPING POINTERS AND GLOBAL SYSTEM SIZE PARAMETERS
C
      COMPLEX RHS(NRSMAX)    
      COMMON /EQVAR/ NEQ,IPS(NLA,NLEQ),ICP(NLA2),IRN(NLA1),IDP(NLA3),
     &               NNA,ISTART(NLA),IRST(NLA),ICST(NLA),NCL(NLA),
     &               NRI(NLA),RHS,IBW,EPS,IRHCOL,NNB
c
c     POINTER ARRAYS SHOULD BE REAL IF APAL64 VERSION OF CVIMOV
C     AND CVMOVI ARE USED ON THE FPS164
C
      INTEGER INDA(NLA1),INDR(NRSMAX),INDS(NRSMAX),INDB(NLA1)
      COMMON /COM_INDEX/ INDA,INDR,INDS,INDB
C
C     SOURCE and RECEIVER PARAMETERS
C
      COMMON /LAYSOU/ NOSOU(NLA),IFSOU(NLA),ILSOU(NLA)
      COMMON /LAYRCV/ NORCV(NLA),IFRCV(NLA),ILRCV(NLA)
C
C     ROUGH SURFACE SCATTERING PARAMETERS
C
      COMMON /SCATCO/ ROUGH(NLA),ROUGH2(NLA)
      COMMON /NKIRCH/ CLEN(NLA),DLWNK(NLA),IMX(NLA)
C
C     TRANSVERSE ISOTROPY
C
      COMPLEX ASP(3,NLA),BSP(3,NLA)
      COMMON /TISO/ NTISOL,NSL(NLA),ASP,BSP,ARO(3,NLA),
     &              AH(3,NLA),LAYNTI(NLA) 
      COMPLEX ANSTD(NTIPAR,NLA)
      COMMON /ANSTD/ ANSTD
C
C     Airy function solution
C
      COMPLEX ACO(NLA),BCO(NLA),CCO(NLA),AISC(NLA),BISC(NLA)
      COMMON /AIRYCO/ ACO,BCO,CCO,AISC,BISC
C
C     WORKING ARRAYS
C
      COMPLEX WORK1(IBSI),WORK2(IBSI)
      COMMON /WORK/ WORK1,WORK2
c
c     Dispersive layers
c
      parameter (mndlt=10, mndfr=500)
      real cpdl(mndlt,mndfr),csdl(mndlt,mndfr),
     &     apdl(mndlt,mndfr),asdl(mndlt,mndfr)
      integer iddis(nla),idltyp(nla)
      logical disper(nla)
      common /dislpa/ cpdl,csdl,apdl,asdl,iddis,nactf,idltyp,
     &                idlmax,disper

