C *** COMMON BLOCKS FOR PULSE PROCESSOR

      DIMENSION RDC(NRD)
      COMMON /PULREC/ RD,RDLOW,RDC,R0,RSPACE,SD

      LOGICAL EQUIRD
      COMMON /PULLOG/ EQUIRD

      CHARACTER*300 FILENAME,OLDFILE,NEWNAME,PLPNAME,PLTNAME,
     &             CDRNAME,BDRNAME,ADRNAME,basename
      CHARACTER*300 FILEN,FILENDAT,FILENBDR
      LOGICAL PLPFILE,CDRFILE,mtvout,mtvplp
      INTEGER LFILNM,IPLCNT,IPART
      COMMON /PULFIL/ LFILNM,IPLCNT,IPART,
     &                FILENAME,OLDFILE,NEWNAME,FILEN,
     &                FILENDAT,FILENBDR,
     &                PLPNAME,PLTNAME,CDRNAME,BDRNAME,ADRNAME,basename,
     &                PLPFILE,CDRFILE,mtvout,mtvplp

      CHARACTER TPLOT,SAVEFILE,SIGNN,PCHOICE(12)
      CHARACTER*6 OPTION(2)
      CHARACTER*80 TITLE,TITLEC
      COMMON /PULCHA/ TPLOT,SAVEFILE,SIGNN,OPTION,
     &                TITLE,TITLEC,PCHOICE

      INTEGER IPARM(12)
      COMMON /PULFBL/ FMIN,FMAX,FMINTRF,FMAXTRF,NFTRF,DLFRQP,DOMEGA,DT,
     &                LX,MX,NX,FCTRF,FQTMP,LXTRF,MXTRF,IPARM,ICDRIN,
     &                isact,isold

      COMMON /PULFLG/ NORMK,NUMINT,IFLAG,ITMP,TSHIFT,TSHTMP

      COMMON /PULSNS/ SCALE,KVAL,ZMINVAL,ZMAXVAL,KSNAPSH1,
     &                ZCMIN,ZCMAX,NCORMK
      logical undfpt
      integer iundef(40000)
      common /pulund/ undfpt,iundef
