      SUBROUTINE EXTLEG(HGTC,IC,LAB,AX,AY,KMIN,NPTS,VXSTA,VYSTA)
      DIMENSION AAX(1),AAY(1),AX(1),AY(1)

      CHARACTER*2 BDEV,FORMT
      CHARACTER*3 PLOP(21),SYMB(20),DEV,ADD,URC,ULC,NWR
      CHARACTER*11 FACTORTMP
      CHARACTER*20 LAB(20)

      COMMON /SETPRM/ PLOP, ADD, BDEV, FACTORTMP,
     &  SYMB, DEV, FORMT, URC, ULC, NWR
      COMMON/XAX/X1,XL,XLEFT,XRIGHT,XSCALE,XINC,DX,
     % X1PL,XDUM4,IXDUM1,XDUM5,XDUM6,XDIV,XVAL(100),NXVAL


      COMMON/YAX/Y1,YL,YUP,YDOWN,YSCALE,YINC,DY,
     % Y1PL,YDUM4,IYDUM1,YDUM5,YDUM6,YDIV,YVAL(100),NYVAL,
     % YBOX

      COMMON /XYLAST/ XLAST,YLAST,XLN,YLN,ISGN

     
       CALL RESET('BLNKS')
      IF(IC.EQ.1 .AND. PLOP(1) .EQ. 'TP ') THEN
       XPOS= XLN + 2.0*HGTC
       YPOS= YLN - 2.0*HGTC
       CALL MESSAG(LAB(3),6,XPOS,YPOS)
      END IF
      CALL HEIGHT( HGTC )
      CALL SCLPIC(1.0)
      CALL MARKER(IC)
      IF(PLOP(1) .EQ. 'ZP ') THEN
         CALL CURVE(AX(KMIN),AY(KMIN),NPTS,-IC)
      ELSE
         CALL CURVE(AX(KMIN),AY(KMIN),NPTS,IC)
      END IF
      TSYY= (YLN -3.0*HGTC) - 2.0*(FLOAT(IC)*HGTC)
      IF(PLOP(1) .EQ. ' P ') THEN
         CALL MESSAG(LAB(11+IC)//'$',11,XLN +0.18 +HGTC,TSYY)
      ELSE IF(PLOP(1) .EQ. 'ZP ') THEN
         CALL MESSAG(LAB(IC)//'$',11,XLN+0.18+HGTC,TSYY)
      ELSE
         CALL MESSAG(LAB(3+IC)//'$',11,XLN + 0.18 + HGTC, TSYY)
      END IF
      AAX(1)= XLEFT + (XLN+0.18)*VXSTA
      AAY(1)= YDOWN + TSYY * VYSTA
      CALL CURVE(AAX,AAY,1,-1)

      RETURN
      END

