      SUBROUTINE SEISL(DEV,IHOR,TITLE,USNAME,NC,N,TRACMM,SAMPMM,
     1                 TRACD,ORIX,ORIY,IDIRX,IDIRY,DZ,KTYPE,NEGPOS,
     2                 KFILL,T0,DT,NTS,NDEC,ICON,Z,IFILE,NLAB,LAB,
     3                 FORMT)
  100 FORMAT(1X,//' **** WARNING:  THIS IS A DUMMY ROUTINE FOR',
     &  ' INSTALLATIONS',
     &  /,'  WHERE THE UNIRAS SOFTWARE IS NOT AVAILABLE ',/,
     &  '  THE ACTUAL ROUTINE IS CALLED "SEISLJUL87" ')
      WRITE(6,100)
      RETURN
      END
