      SUBROUTINE IPEOLD(Z,NZX,NZY,FREQ,SD,FORM)
      PARAMETER (NLEV1=51)
      CHARACTER*3 XBTYPE, YBTYPE, FORM, SDPLOT, RDPLOT
      CHARACTER*4 TITLE,TITLEX,TITLEY
      CHARACTER*80 FILENM
      DIMENSION Z(NZX,NZY)
CCCCCC      COMMON /BOTT/ XF(220), YF(220), NPBOTT, ISHADE, NPSH
      COMMON /PARA/ LABPT,NSM,NDIV,CAY,NARC,NRNG,HGTPT,HGT,
     & LABC(51),LWGT(51)
      COMMON /PARAC/ TITLE(20), SDPLOT, RDPLOT
      COMMON /XAX/ X1,XL,XLEFT,XRIGHT,XSCALE,XINC,DX,
     & X1PL,XLPL,NX,X1GRID,XLGRID,DIVX,XVAL(100),NXVAL
      COMMON /XAXC/ TITLEX(20),XBTYPE
      COMMON /YAX/ Y1,YL,YUP,YDOWN,YSCALE,YINC,DY,
     & Y1PL,YLPL,NY,Y1GRID,YLGRID,DIVY,YVAL(100),NYVAL
      COMMON /YAXC/ TITLEY(20),YBTYPE
      COMMON /ZAX/ ZMIN,ZMAX,ZINC,NLEV,ZLEV(NLEV1)

  300 FORMAT(A80)
  400 FORMAT(20A4)
  500 FORMAT(4E15.8)
  600 FORMAT(1X,'NLEV = ',' THIS PROGRAM ALLOWS ONLY 51 LEVELS FOR',
     &' CONTOURING',/,'EXECUTION TERMINATED')
  700 FORMAT(1X,'NX,NY TOO LARGE',/,1X,'EXECUTION',
     & 1X,'TERMINATED BECAUSE OF ARRAY SIZE LIMITATIONS',/)
C
      TITLEX(1)='Rang'
      TITLEX(2)='e (k'
      TITLEX(3)='m)$ '
      TITLEY(1)='Dept'
      TITLEY(2)='h (m'
      TITLEY(3)=')$  '
      DO 1000   I=4,20
      TITLEX(I)='    '
      TITLEY(I)='    '
 1000 CONTINUE
      X1PL=1.5
      Y1PL=1.5
      LABC(1)=-1
      LWGT(1)=0
      HGTPT=0.1
      HGT=0.14
      LABPT=-3
      NDIV=1
      NARC=5 
      XBTYPE='LIN'
      YBTYPE='LIN'
C
      READ(55,300)FILENM
      IF(FORM.EQ.'BIN')   THEN
       OPEN(UNIT=17,file=filenm,STATUS='OLD',
     & FORM='UNFORMATTED')
      ELSE
       OPEN(UNIT=17,file=filenm,STATUS='OLD',
     & FORM='FORMATTED')
      END IF
      READ(55,*)NX,NY
C
      IF(NX*NY.GT.NZX*NZY)   THEN
       WRITE(6,700)
       STOP
      END IF
C
      READ(55,400)TITLE
      READ(55,*)FREQ,SD
      SDPLOT='m  '
      READ(55,500)X1,XL,XAXIS,XINC
      DIVX=1.0E-3
      XLEFT=X1
      XRIGHT=XL
      X1GRID=X1
C
C  NEXT STATEMENT MAY BECOME USEFUL IF XL AND XRIGHT ARE
C  INDEPENDENTLY DEFINED.
C
      XLGRID=AMIN1(XRIGHT,XL)
C
      XSCALE=ABS((XL-X1)/XAXIS)
      READ(55,500)Y1,YL,YAXIS,YINC
      DIVY=1.0
      YUP=Y1
      YDOWN=YL
      Y1GRID=YDOWN
      YLGRID=YUP
      YSCALE=ABS((YL-Y1)/YAXIS)
      READ(55,*)ZMIN,ZMAX,ZINC,NSM

CCCCCC      CALL BOTTOM

CCCCCC      IF(NPBOTT.GE.2)   THEN
CCCCCC       DO 1300   I2=NPBOTT,1,-1
CCCCCC       IF(XF(I2).LE.XRIGHT)   GO TO 1400
CCCCCC 1300  CONTINUE
CCCCCC 1400  CONTINUE
CCCCCC       DO 1500   I1=1,I2
CCCCCC       IF(XF(I1).GE.XLEFT)   GO TO 1600
CCCCCC 1500  CONTINUE
CCCCCC 1600  CONTINUE
CCCCCC       DO 1800   I=I1,I2
CCCCCC       XF(I-I1+1)=XF(I)
CCCCCC       YF(I-I1+1)=YF(I)
CCCCCC 1800  CONTINUE
CCCCCC       NPBOTT=I2-I1+1
CCCCCC      END IF
CCCCCC
CCCCCC      IF(NPBOTT.LT.2)   THEN
CCCCCC       WRITE(6,*) ' REVISE BOTTOM DESCRIPTION '
CCCCCC       WRITE(6,*) ' ERROR DETECTED IN SUB BOTTOM '
CCCCCC       STOP 
CCCCCC      END IF

 2100 LWGT1=LWGT(1)
      IF(ABS(ZINC).GT.0.0)   GO TO 2200
      NLEV=1
      ZLEV(1)=ZMIN
      GO TO 2800
 2200 CONTINUE
      NLEV=ABS((ZMAX-ZMIN)/ZINC)+1
      IF(NLEV.LE.NLEV1)   GO TO 2400
      WRITE(6,600)NLEV
      STOP
 2400 CONTINUE
      DO 2600 I=1,NLEV
      LABC(I)=LABC(1)
      ZLEV(I)=(I-1)*ZINC+ZMIN
      LWGT(I)=LWGT1
      IF(MOD(NINT(ZLEV(I)),10).EQ.0 )LWGT(I)=LWGT1+1
 2600 CONTINUE
 2800 CONTINUE
C
C     READ CONTOUR DATA FROM FILE 17.
C
      CALL READPE(Z,NX,NY,FORM)
C      CLOSE(17)
       RETURN
       END
