      SUBROUTINE NEWGCOL(INDEX,CODE1,CODE2,CODE3,NCOL)

      INTEGER INDEX, CODE1(1), CODE2(1), CODE3(1), NCOL
      REAL COLOR(3), HATCH(5)

      MODE= 0
C  MODE=0   : RCOLOR DEFINES THE COLOR
C  MODE=2   : RCOLOR DEFINES THE HATCH PATTERN
C  MODE= 3  : RCOLOR DEFINES BOTH 

      DO 1000   I=1,NCOL
      COLOR(1)= CODE1(I)
      COLOR(2)= CODE2(I)
      COLOR(3)= CODE3(I)
      CALL RCOLOR(0,INDEX+I-1,COLOR,HATCH)
 1000 CONTINUE

      RETURN
      END
