      SUBROUTINE NOVALUE(SDFLAG,VALUE,LUNIT,SDUNIT)
      CHARACTER*28 SDUNIT
      CHARACTER*15 SDCHAR,SDBLK
      DATA SDBLK/' '/
  200 FORMAT(1X,A15)
  300 FORMAT(F15.4)
  420 FORMAT(1X,A15,3X,A28)
      READ(LUNIT,420) SDCHAR, SDUNIT
      IF(SDCHAR .NE. SDBLK)   THEN
       SDFLAG=0.0
       READ(SDCHAR,300) VALUE
C       WRITE(6,*) ' VALUE : ',VALUE
      ELSE
       SDFLAG=1.0
      END IF
C      WRITE(6,*) ' SDCHAR :'
C      WRITE(6,200) SDCHAR
C      WRITE(6,*) ' FLAG : ',SDFLAG
C     RETURN
      END

