      SUBROUTINE SAMPLE(Z,NXOLD,NYOLD,NX,NY,X1,XL,Y1,YL,LU)
      DIMENSION Z(NXOLD,NYOLD)
C
C INTERPOLATION ALONG THE X AXIS STARTS HERE
C
      IF(NX.EQ.NXOLD)   GO TO 4000
      DX=(XL-X1)/(NX-1)
      DXOLD=(XL-X1)/(NXOLD-1)
      DO 2000 JX=2,NX-1
      X=(JX-1)*DX
      I1=X/DXOLD+1
      XA=(I1-1)*DXOLD
      I2=I1+1
      XB=XA+DXOLD
      DO 2000 JY=1,NYOLD
      Z(JX,JY)=Z(I1,JY)+((Z(I2,JY)-Z(I1,JY))/(XB-XA))*(X-XA)
2000  CONTINUE
C
      DO 3000 JY=1,NYOLD
      Z(NX,JY)=Z(NXOLD,JY)
3000  CONTINUE
C
 4000 CONTINUE
      IF(NY.EQ.NYOLD)   GO TO 6000
C
C INTERPOLATION ALONG THE Y AXIS STARTS HERE
C 
C 
      DY=(YL-Y1)/(NY-1)
      DYOLD=(YL-Y1)/(NYOLD-1)
      DO 5000 JY=2,NY-1
      Y=(JY-1)*DY
      I1=Y/DYOLD+1
      YA=(I1-1)*DYOLD
      I2=I1+1
      YB=YA+DYOLD
      DO 5000 JX=1,NX
      Z(JX,JY)=Z(JX,I1)+((Z(JX,I2)-Z(JX,I1))/(YB-YA))*(Y-YA)
5000  CONTINUE
C
 6000 CONTINUE
C
      DO 6500   JX=1,NX
      Z(JX,NY)=Z(JX,NYOLD)
 6500 CONTINUE
C
      DO 7000 JY=1,NY
      WRITE(LU)(Z(JX,JY),JX=1,NX)
7000  CONTINUE
      REWIND LU
      RETURN
      END
