      SUBROUTINE XAXLIN
      CHARACTER*3 XBTYPE
      CHARACTER*80 TITLEX
      COMMON /XAX/X1,XL,XLEFT,XRIGHT,XSCALE,XINC,DX,
     % X1PL,XLPL,NX,X1GRID,XLGRID,DIVX,XVAL(100),NXVAL
      COMMON /XAXC/TITLEX,XBTYPE
      COMMON /PARA/LABPT,NSM,NDIV,CAY,NARC,NRNG,HGTPT,HGT,
     % LABC(51),LWGT(51)
C
      CALL NUMDEC(XLEFT,XRIGHT,XINC,DIVX,NDEC)
      NDEC=MAX0(-1,NDEC)
C
      ABSINC=ABS(XINC)
      IF(XRIGHT.LT.XLEFT)   XINC=-ABSINC
      HGTCH=HGT
      XAXIS=ABS((XRIGHT-XLEFT)/(XSCALE*2.54))
      DX=XAXIS/(XRIGHT-XLEFT)
      NINC=ABS((XRIGHT-XLEFT)/XINC)+1
      CALL PLOT(0.,0.,3)
      DO   10   I=1,NINC
      X=(DX*XINC)*(I-1)
      CALL PLOT(X,0.,2)
      CALL PLOT(X,0.1,2)
      XNUMB=((I-1)*XINC+XLEFT)*DIVX
      XN=ABS(XNUMB)
      IF(XN.LT.10.0)   XN=1.
      N=ABS(ALOG10(XN))+2 + NDEC
      IF(XNUMB.LT.0.0)   N=N+1
      XV=X-N*HGTCH/2.
      Y=-0.8*HGTCH
      CALL NUMBER(XV,Y-HGTCH,HGTCH,XNUMB,0.,NDEC)
   10 CALL PLOT(X,0.,3)
      CALL PLOT(XAXIS,0.,2)

      CALL CHARA(TITLEX,NC)
      Y= -2.8*HGTCH 
      HGTCH=1.5*HGT
      X=(XAXIS-NC*HGTCH)/2.
C      X=MIN(-N*HGTCH*0.47,X)
      CALL SYMBOL(X,Y-HGTCH,HGTCH,TITLEX,0.,NC)
      RETURN
      END
