      SUBROUTINE YAXLIN
      CHARACTER*3 YBTYPE
      CHARACTER*80 TITLEY
      COMMON /YAX/Y1,YL,YUP,YDOWN,YSCALE,YINC,DY,
     % Y1PL,YLPL,NY,Y1GRID,YLGRID,DIVY,YVAL(100),NYVAL
      COMMON /YAXC/TITLEY, YBTYPE
      COMMON /PARA/LABPT,NSM,NDIV,CAY,NARC,NRNG,HGTPT,HGT,
     % LABC(51),LWGT(51)
C
      CALL NUMDEC(YUP,YDOWN,YINC,DIVY,NDEC)
      NDEC=MAX(-1, NDEC)
C
      ABSINC=ABS(YINC)
      IF(YUP.GT.YDOWN)   ABSINC=-ABSINC
      HGTCH=HGT
      YAXIS=ABS((YDOWN-YUP)/(YSCALE*2.54))
      DY=YAXIS/(YUP-YDOWN)
      NINC=ABS((YDOWN-YUP)/YINC)+1
      CALL PLOT(0.,0.,3)
      CALL PLOT(0.,YAXIS,2)
      XMIN=0.0
      DO   10   I=NINC,1,-1
      Y=YAXIS-ABS(YINC*(NINC-I)*DY)
      CALL PLOT(0.,Y,3)
      CALL PLOT(0.1,Y,2)
      YNUMB=(YUP+(NINC-I)*ABSINC)*DIVY
      YN=ABS(YNUMB)
      IF(YN.LT.10.0)   YN=1.
      N=ABS(ALOG10(YN))+3 + NDEC
      IF(YNUMB.LT.0.0)   N=N+1
      X=-N*HGTCH
      XMIN= MIN(XMIN,X)
      CALL NUMBER(X,Y,HGTCH,YNUMB,0.,NDEC)
   10 CALL PLOT(0.,Y,3)
C  COUNT OF NON-BLANK WORDS OF TITLEY
      CALL CHARA(TITLEY,N)
      HGTCH=1.5*HGT
      Y=(YAXIS-N*HGTCH)/2.
      CALL SYMBOL(XMIN - HGT,Y,HGTCH,TITLEY,90.,N)
      RETURN
      END
