      SUBROUTINE YLOG
C
      COMMON /YAX/Y1,YL,YUP,YDOWN,YSCALE,YINC,DY,
     % Y1PL,YLPL,NY,Y1GRID,YLGRID,DIVY,YVAL(100),NYVAL
C
  200 FORMAT(1X,'EXECUTION TERMINATED BECAUSE OF ARRAY LIMITATIONS',/
     % ,'  ERROR OCCURRED IN SUBROUTINE YLOG ')
C
      Y1=ALOG(Y1)/ALOG(2.0)
      YL=ALOG(YL)/ALOG(2.0)
      NYVAL=NINT(ABS(ALOG(YUP/YDOWN)/ALOG(2.0))*YINC+1.01)
      IF(NYVAL.GT.100)THEN
      WRITE(6,200)
      STOP
      END IF
      YSIGN=SIGN(1.0,YDOWN-YUP)
      DO 1000 I=NYVAL,1,-1
      YVAL(I)=DIVY*YUP*2.0**(YSIGN*((I-1)/YINC))
 1000 CONTINUE
      RETURN
      END
