      COMPLEX CRP(nrnr),CRPX(nrnr),CRPY(nrnr),CRPZ(nrnr)
      COMPLEX CNINV(nrnr),EMAT(NRNP),PATKN(NRMAX),UWGHT(NPMAX)
      COMPLEX EBUF1(NPNP),EBUF2(NPNP)
      COMMON /PESBUF/ CRP,CRPX,CRPY,CRPZ,CNINV,EMAT,PATKN,UWGHT,
     &                EBUF1,EBUF2




